#!/usr/bin/env python

from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

import muscle


database_uri = 'mysql://muscle_test:foobar@localhost/muscle_test'

Base = declarative_base()


class Foo(Base):
    __tablename__ = 'foo'

    id = Column(Integer, primary_key=True)
    bar = Column(String(30))


print '*** ex1: Create Table ***'

engine = create_engine(database_uri)
muscle.expand(engine, Base.metadata)	# Should create foo table

Session = sessionmaker(bind=engine)
session = Session()

# Insert some example data
foo1 = Foo()
foo1.bar = 'This is a string'
session.add(foo1)

foo2 = Foo()
foo2.bar = 'This is a longer string'
session.add(foo2)

session.commit()
