#!/usr/bin/env python

from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

import migrations
import muscle


database_uri = 'mysql://muscle_test:foobar@localhost/muscle_test'

Base = declarative_base()


class Foo(Base):
    __tablename__ = 'foo'

    id = Column(Integer, primary_key=True)
    baz = Column(Text)


print
print '*** ex3: Contract foo.bar ***'

engine = create_engine(database_uri)
current = muscle.contract(engine, Base.metadata)
muscle.patch(current, locals())

Session = sessionmaker(bind=engine)
session = Session()

for row in session.query(Foo):
    print muscle.dictify(row)
